### ISSUE TITLE
How to access class properties and static factories?

### ISSUE THREAD

**Issue by marcospassos** [belgattitude/soluble-japha#37]
How to handle this simple case using the bridge?

```java
EnumSet set = EnumSet.of(CustomEnum.FOO);
```

**Comment by belgattitude** [comment]
Hi Marcos,

You should be able do to something like below:

```php
$formatStyle = $ba->java('java.time.format.FormatStyle');
$enumSetClass = $ba->javaClass('java.util.EnumSet');
$mySet = $enumSetClass->of($formatStyle->LONG, $formatStyle->SHORT);
echo (string) $mySet->toString(); // -> will print '[LONG, SHORT]'
```
Note the use of `$ba->javaClass('java.util.EnumSet`) instead of `$ba->java(...)`. You can refer to the documentation to understand their differences [here](http://docs.soluble.io/soluble-japha/language_basics/#classes).

I've also added a unit test about it, have a look at 

https://github.com/belgattitude/soluble-japha/blob/master/test/src/SolubleTest/Japha/Bridge/AdapterUsageUtilTest.php#L88

to complete the picture.

Let me know if it helps, so I'll close the issue... I'll update the doc once back from holidays, but if you have any comment, ideas, questions... to help for doc, the are very welcome.

Thanks for asking

**Comment by marcospassos** [comment]
@belgattitude first of all, thank you for supporting such an amazing project like this. We're in means of evaluating the bridge to use in a huge project. So, you will see us around more often :)

> Let me know if it helps, so I'll close the issue... I'll update the doc once back from holidays, but if you have any comment, ideas, questions... to help for doc, the are very welcome.

Yes, it works smoothly. Thank you!

**Comment by belgattitude** [comment]
Great !

Out of curiosity, will your project will be php7.0 only.... I would love to release a v2, dropping pre-7 support soon, but not sure if it's the right time to do it

**Comment by marcospassos** [comment]
Yes. In fact it is 7.1+
