### ISSUE TITLE
Add support for inner classes

### ISSUE THREAD

**Issue by marcospassos** [belgattitude/soluble-japha#38]
Looks like inner classes are not currently supported:

```java
$inner = $ba->java('com.acme.ClassName.InnerClass');
```
Error
```
CreateInstance failed: new com.acme.ClassName.InnerClass. Cause: java.lang.ClassNotFoundException: com.acme.ClassName.InnerClass VM: 1.8.0_121@http://java.oracle.com/
```

**Comment by belgattitude** [comment]
Hey Marcos,

Not sure about this one, the bridge cannot implicitly make the difference between an inner class and a package namespace... and searched for the `com.acme.ClassName.<RegularX>Class` instead.

Can you try with the `$` separator instead of the dot like this:

```
$inner = $ba->java('com.acme.ClassName$InnerClass');
```

> Be sure to use single quotes, otherwise the `$` sign will be interpreted on the php side.

Let me know if it works for you ? I'll update the doc accordingly.

Thanks

**Comment by marcospassos** [comment]
Yes, it works. I'd recommend you to make it part of the documentation.

Thank you again!

**Comment by belgattitude** [comment]
Hi Marcos,

Reopening the issue till the doc is fine. I've added a test case based on [java.util.Calendar.Builder](https://docs.oracle.com/javase/8/docs/api/java/util/Calendar.Builder.html) inner class...

See the unit test: https://github.com/belgattitude/soluble-japha/blob/master/test/src/SolubleTest/Japha/Bridge/AdapterUsageInnerClassTest.php#L46

**Comment by belgattitude** [comment]
Doc added in http://docs.soluble.io/soluble-japha/language_basics/#inner-classes
