### ISSUE TITLE
Provide more information about performance issues

### ISSUE THREAD

**Issue by marcospassos** [belgattitude/soluble-japha#39]
We realized that the documentation does not cover relevant questions about performance:

- Does every property access trigger a round trip?
- Does every static property access trigger a round trip?
- Does a class reference through `$bridge->javaClass(...)` trigger a round trip?

We'd  like to suggest adding these topics to the documentation once performance is one of the most important aspects when considering to use bridges.

**Comment by belgattitude** [comment]
Hi Marcos,

For performance and an extensive usage of java objects, I would not use the bridge ;) 

> If not done, you can read the [considerations](http://docs.soluble.io/soluble-japha/#considerations). 

The trick with the bridge is that it only keeps a reference to the remote Java object (a remote proxy)... So whatever you call on your "php proxied objects" (method, property access), they will be forwarded to their corresponding part on the JVM side (roundtrip -> from 0.01ms to ???ms depending on the data transfert if any - i.e a method that returns a 30Mb text will create more traffic than a factory which only create a reference to the object).

I might have a look to the current benchmarks... but not as a priority. Simply because that all tests could potentially give too much different results (i.e. timing of an integer property access will be different from a date...):

Also with benchmarks, a single call cost generally more than multiple repetitive ones, ... Optimizations and JIT happens on the java side, not even talking of JVM garbage collection that might change the rules when it happens... (will also happen in any Java program). So very difficult to establish a realistic benchmark. 

My point is, you should first get a typical use case (will you use a specific java library ? How many method call you expect...) and see how it goes. 

And yes that could be nice to have some positive, encouraging insights in the doc. But as It really depends on the use cases, I would have the impression to lie ;) For my part I use it very successfully for projects like jasper report generation, exchange MAPI integration, enterprise ERP... even high scale. But I always fall back to writing a Java API when the code is complex and I don't need too much freedom on the PHP side.

Anyway thanks for your remark, and let me know your usage so I can eventually give you some recommendations.

**Comment by belgattitude** [comment]
But something that could be nice is to compare a regular API with a bridge implementation. If you have ideas  of a program I can make one.... and see

**Comment by marcospassos** [comment]
Our use case is pretty simple. We have a parser at the Java side that produces syntax trees. We use the bridge to parse expressions in Java, but handle the information on the PHP side (because our core is written in PHP). To reduce the number of roundtrips, we've implemented a facade on the Java side. So now we've just a couple of calls to perform: we use enums to configure a builder (looks like every enum constant counts as one round trip) that creates the parser and finally, we call the method that parses the expression. Long story short, in the worst scenario, we make use of 15 enum references, 5 objects (1 x builder instance + 2 x parser instances + 2 x EnumSet instances), and 2 method calls.

Given this scenario, the most performance expensive part is the enum references. Do you have any tip of how improving it?

**Comment by belgattitude** [comment]
Just finished my day, and will find time tomorrow. Be sure to not recreate enums, i.e

Instead of:
```php
$formatStyle = $ba->java('java.time.format.FormatStyle');
foreach(....) {
    $enumSetClass = $ba->javaClass('java.util.EnumSet');
    $mySet = $enumSetClass->of($formatStyle->LONG, $formatStyle->SHORT);
}
```
Something like this:

```php
$formatStyle = $ba->java('java.time.format.FormatStyle');
$longFormat = $formatStyle->LONG;
$shortFormat = $formatStyle->SHORT;
$enumSetClass = $ba->javaClass('java.util.EnumSet');
foreach(....) {
    $mySet = $enumSetClass->of($longFormat, $shortFormat);
}
```

Also note that iterator is not performant at all and sometimes better to use `$ba->values()`, see the optimization techniques... 

I guess you already do that, but in case...

**Comment by marcospassos** [comment]
This is exactly what we do, thanks! :)

Additionally, is there any reason for property references not be lazily loaded? Making constants and properties lazily loaded would save lots of round trips and improve performance. The reference is resolved when A) the value is required (a print statement or a casting operation, such as a `toString()` call) or B) an operation that requires the value to be resolved. In that case, the value resolution could be done on the Java side, so a single roundtrip would be required if only scalar values or property references are used.

**Comment by marcospassos** [comment]
Of course, there are some implications related to the object state that can change while the reference is not resolved, but a new method (in the same vein of `->values()`) could address it. It makes explicit that using this method the return will be a promise.

```php
// 0 round trips
$enum = $bridge->javaReference('acme.foo.Bar');
$promise = $enum->CONSTANT;

// 1st roundtrip
$object= $bridge->java('acme.foo.FooBar');
// 2nd roundtrip
$object->call($promise);
```

**Comment by belgattitude** [comment]
Hi Marcos,

Thanks, not sure about it... In your scenario the promise will have to be resolved in the java side, and will really make things complex (how the bridge knows how to resolve the method signature (overloading) ?)... and I believe it may lead to a lot of debugging issues. We'll improve the roundtrips for sure, but the java side will have more work on every method selection... I don't know if you benchmarked a roundtrip, but it's about 0.05ms on my laptop for javaClass... 

If I had to tackle optimizations I would first look to http2 support (and protocol buffers, json - need tests to see).. But that's another story.

But good, I'll think about it overnight. 

Thanks

**Comment by belgattitude** [comment]
@marcospassos 

a good news for the last question concerning `javaClass` and the possible roundtrips. 

Classes are cached internally by the client (one version for every FQDN)... so no roundtrips here.

On my laptop:

| Benchmark name |  x1 | x100 | x1000 | x10000 | Average | Memory |
|----| ----:|----:|----:|----:|-------:|----:| 
| New java(`java.math.BigInteger`, 1) | 0.06ms| 2.98ms| 26.05ms| 286.36ms| 0.03ms| 0.37Kb|
| `$ba->javaClass('java.sql.DriverManager')` | 0.09ms| 0.02ms| 0.14ms| 1.69ms| 0.00ms| 3.12Kb|

You can see the (php) memory increases, but after the first call, the new ones are pretty fast.
I've updated the doc and prepared a new version 1.2.2.

Thanks

**Comment by marcospassos** [comment]
Good news! About the Enums, does every constant reference trigger a roundtrip?

**Comment by belgattitude** [comment]
Should have checked ;) Yes it makes a roundtrip, unfortunately...

Time:

| Benchmark name |  x1 | x100 | x1000 | x10000 | Average | Memory |
|----| ----:|----:|----:|----:|-------:|----:| 
| New java(`java.math.BigInteger`, 1) | 0.04ms| 3.12ms| 31.77ms| 286.99ms| 0.03ms| 0.37Kb|
| javaClass(`java.sql.DriverManager`) | 0.14ms| 0.02ms| 0.15ms| 1.48ms| 0.00ms| 67.12Kb|
| javaClass and enums | 0.06ms| 2.04ms| 25.18ms| 225.67ms| 0.02ms| 2.12Kb|

That could be improved, but not so easy... If you have an idea ? It will need to done on both server and client, but the initial time will be greater then... 

Saving a local php variable is better ?  What do you think ?
