### ISSUE TITLE
Make __get, __call and __set part of JavaObject API

### ISSUE THREAD

**Issue by marcospassos** [belgattitude/soluble-japha#44]
Currently, the API does not guarantee support for calling magic methods on objects or classes:

```php
// Returns JavaObject
$object = $bridge->java('...');
// Returns JavaClass
$class = $bridge->javaClass('...');
```

It's a bad design: we're coding against an interface, but the magic methods are tied to an implementation. 

I would like to suggest two changes: 1) add the magic methods to the interface and 2) add non-magic methods (for non-magician developers : ) to get/set properties and call methods.

**Comment by marcospassos** [comment]
As a side note, I'm currently type-hinting against  `Soluble\Japha\Bridge\Driver\Pjb62\Java` and `Soluble\Japha\Bridge\Driver\Pjb62\JavaClass` but, of course, it is not the best option.

**Comment by belgattitude** [comment]
Hi @marcospassos ,

great addition yes... thanks for pointing out.

Could you have a look to my latest commit: https://github.com/belgattitude/soluble-japha/commit/038eb5627bd33267fd0a7900adcdd75deed4cb50

I admit I didn't get the second point:

> 2) add non-magic methods (for non-magician developers : ) to get/set properties and call methods.

Could you explain a little more ?

**Comment by marcospassos** [comment]
Hi @belgattitude, thanks for your always quick feedback!

Yes, 038eb56 looks great, thank you.

About the second point, it is just an enhancement. The idea is to introduce methods to instrument the API without straight calling the magic methods:
```php
$result = $object->call('method', ...$arg); // instead of $obect->__call(...)
$value = $object->get('property'); // instead of $obect->__get(...)
$object->set('property', $value); // // instead of $obect->__set(...)
```

Again, it's just a suggestion :).

**Comment by marcospassos** [comment]
A possible problem is conflicting with real Java methods.

**Comment by belgattitude** [comment]
Hi @marcospassos,

Got it thanks! 

My problem here is that the `Interfaces\JavaObject` delegates to possibly every JavaObject method or property that exists... So where to limit ?

My point, and I already started something, is to create PHP implementation of most common objects. I'm not yet decided on how to do it but you can refer for example to the [Util\TimeZone.php](https://github.com/belgattitude/soluble-japha/blob/master/src/Soluble/Japha/Util/TimeZone.php) or  [Db\DriverManager.php](https://github.com/belgattitude/soluble-japha/blob/master/src/Soluble/Japha/Db/DriverManager.php)

They are not documented yet because I'm not yet happy with the implementation and would not like to run into bc-break issues later on in the project.

With that in mind, I would be open to implement some of the most common Java objects (HashMap, ...) as helpers. But first ensure we have an good implementation.

**Comment by belgattitude** [comment]
Side note: I'm about to release the 1.4.0 version with the JavaObject interfaces changes. Just waiting an hour or two to let you jump in if you think about something more.

Thanks,

Seb

**Comment by belgattitude** [comment]
@marcospassos : read your example with

```php
$result = $object->call('method', ...$arg); // instead of $obect->__call(...)
$value = $object->get('property'); // instead of $obect->__get(...)
$object->set('property', $value); // // instead of $obect->__set(...)
```

Yes it will create conflict with any set or get method on the java object... Better to work out with magics ;)

I'll close the issue for now, feel free to reopen
