### ISSUE TITLE
Error: Class 'Soluble\Japha\Bridge\Adapter' not found

### ISSUE THREAD

**Issue by BeachyHeadCode** [belgattitude/soluble-japha#50]
I am trying to call the Adapter class and it is not found. All my other classes I have installed on composer are found when using get_declared_classes().  Even Psr/Log/NullLogger is found. I think you have something wrong in your composer.json file. I have mine set to "soluble/japha": "^2.6.4",

**Comment by belgattitude** [comment]
Hi @MrPlow254 

Cannot reproduce... But can you double check if your composer install is fine...

Steps to try:

1. Ensure you have well loaded composer autoload file `require vendor/autoload.php`. (I guess it's fine, most frameworks do it automatically. Otherwise you need to first include this file)
2. Checks that the `vendor/composer/autoloader_psr4.php` have been generated and contains at least:

```php
'Soluble\\Japha\\' => array($vendorDir . '/soluble/japha/src/Soluble/Japha'),
```

Let me know

**Comment by BeachyHeadCode** [comment]
Okay, just reinstalled composer. Seems to work now.
